shoppingflux/module-prestashop

shoppingfeed.php
src/OrderImport/Rules/ZalandoCarrier.php
src/OrderImport/Rules/ZalandoColissimo.php
upgrade/install-1.6.3.php

| Description?  | Zalando don't supply the carrier name. That may cause trouble for merchand that want map to a carrier different than Colissimo
| Fixed ticket? | Fixes 34027
| How to test?  | Use Unit test

bugfix #34027 - add rule for zalando when carrier is empty

---

202/tests/OrderImport/OrderImportSimpleTest.php
src/OrderImport/Rules/ZalandoCarrier.php

| Description?  | Zalando don't supply the carrier name. That may cause trouble for merchand that want map to a carrier different than Colissimo
| Fixed ticket? | Fixes #34027
| How to test?  | Use Unit test

bugfix #34027 - fix condition isApplicable

---

controllers/front/syncOrder.php

| Description?  | In case of shipped by MarketPlace but without "already shipped" import order, orders shipped by MarketPlace are not imported.
| Fixed ticket? | Fixes 34645
| How to test?  | See support tickets.

Add shipped by marketplace on getUnacknowledgedOrders

---

.github/workflows/phpunit.yml
202/docker/Dockerfile
202/docker/entrypoint.sh
202/docker/run_for_unittest.sh
202/tests/OrderImport/OrderImportSimpleTest.php
classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | If imported order need apply a tax rules with VAT and a second tax like TPH, the module dosn't compute the good taxes amounts.
| Fixed ticket? | Fixes 34618
| How to test?  | Unit tests added

fix amount of tax in case of tax rules with several taxes

---

202/tests/OrderSync/TaskOrderCleanerTest.php
classes/ShoppingfeedOrder.php
classes/actions/ShoppingfeedOrderSyncActions.php
src/Services/TaskOrderCleaner.php
upgrade/install-1.8.0.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_static.php

| Description?  | In case of mismatch between the order state on PrestaShop and ShoppingFeed, the module retry to send PrestaShop state that trigger a failed response.<br>The module sould send the error only once and retry only during 7 days
| Fixed ticket? | Fixes 34100
| How to test?  | Cover by Unit tests

Disabled old order sync ticket 

---

202/docker/run_for_unittest.sh
202/tests/OrderImport/OrderImportSimpleTest.php
202/tests/OrderImport/OrderSplittingTest.php
202/tests/OrderImport/dataset/order-for-splitting.json
classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | In case of splitted order due to specific carriers set on each items of an order, the summary of each order is not OK.
| Fixed ticket? | Fixes 33703
| How to test?  | Tested by Unit Test

Recalculating splitted order

---

shoppingfeed.php
upgrade/install-1.8.0.php

| Description?  | Fix regression during upgrade 1.7 to 1.8 of this module.
| Fixed ticket? | Fixes #35437
| How to test?  | Try to upgrade from 1.7 to 1.8

Regression during upgrade 1.7 to 1.8: class Hook not found

---

controllers/front/product.php
src/Services/ProductAttributeCombination.php
src/Services/ProductSerializer.php
vendor/shoppingfeed/php-feed-generator/src/Product/AbstractProduct.php
vendor/shoppingfeed/php-feed-generator/src/Product/Product.php
vendor/shoppingfeed/php-feed-generator/src/Xml/XmlProductFeedWriter.php

| Description?  | Add ecotax value on product's variations if general setting PS_ECOTAX is enabled
| Fixed ticket? | Fixes #35844
| How to test?  | Enable Ecotax on PrestaShop, add an ecotax on a product with  declinaison. All variations on the product XML feed should have a node with ecotax.

Add ecotax value on product's variations

---

controllers/admin/AdminShoppingfeedOrderImportRules.php

| Description?  | regression. Save order settings not available 
| Fixed ticket? | Fixes 36123
| How to test?  | try to save order settings in the module.

refs #36123 order configuration are not saved

---

controllers/admin/AdminShoppingfeedDiagnostic.php
src/OrderImport/Rules/AbstractMondialrelay.php
vendor/totpsclasslib/src/Extensions/Diagnostic/Stubs/Handler/LogsStubHandler.php

| Description?  | AbstractMondialRelay bloque AdminShoppingfeedOrderImportRulesController<br>Diagnostic Tab is KO due to 500 error
| Fixed ticket? | Fixes 36360
| How to test?  | View support on 1.6.1.5 PHP 7.0

Fixies on php 7.0- and PS 1.6

---

controllers/admin/AdminShoppingfeedGeneralSettings.php

| Fixed ticket? | Fixes #36621
| How to test?  | enable debug mode and go to  "Products feed" tab

refs #36621 - fix error when get product feed rule filters

---

src/Services/ProductSerializer.php

| Description?  | On a multishop environment, multitoken SF.<br>When a product is only activated for one shop, the module doesn't take into account the shop id connected with the token. 
| Fixed ticket? | Fixes 36953
| How to test?  | -

Bug multishop, stock updates when product is only activated for one shop (36953)

---

src/Hook/ActionShoppingfeedTracking/RelaisColis.php
src/OrderImport/Rules/RelaisColisRule.php
src/OrderImport/Rules/ShippedByMarketplace.php

| Description?  | catch warning during the order import in case of missing product translations
| Fixed ticket? | Fixes 37365
| How to test?  | Due to data integrity of the merchand... not testable

catch warning during the order import in case of missing product translations (37365)

---

src/OrderImport/Rules/AbstractColissimo.php

| Description?  | Padd default phone mobile for order with colissimo.
| Fixed ticket? | Fixes #36642

refs#36642 - add default phone mobile for order with colissimo

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | remove a discount from invoice. It seems the problem arrives when the PS generates an order invoice before the module recalculates the prices (hook actionValidateOrder). 
| Fixed ticket? | Fixes 37710
| How to test?  | unit tested

Fixbug: remove a discount from invoice (37710)

---

controllers/admin/AdminShoppingfeedGeneralSettings.php
controllers/front/product.php
views/templates/admin/shoppingfeed_general_settings/products_feeds.tpl

| Description?  | get product feed under token only
| BC breaks?    | yes, url without token return now 401
| Fixed ticket? | Fixes 37103
| How to test?  | visit the url of product feed with and without token

Add token as mandatory to get product xml feed (37103)

---

202/tests/OrderImport/OrderShippedByMarketplaceTest.php
src/OrderImport/RuleAbstract.php
src/OrderImport/Rules/ShippedByMarketplace.php

| Description?  | The merchant configuration of SF module is : import shipped status to YES, Import orders shipped by Market place to NO<br>Orders shipped by Market place are imported in error in logs.
| Fixed ticket? | Fixes 38044
| How to test?  | Unit tested

Order shipped by marketplace imported in error (38044)

---

202/docker/run_for_unittest.sh
202/tests/ProductSerializer/TestAttributeTestCase.php
controllers/front/product.php
src/Services/ProductAttributeCombination.php
src/Services/ProductSerializer.php

| Description?  | add ecotax in product variation attributes.
| BC breaks?    |no
| Fixed ticket? | Fixes #38070

Add ecotax in product variation attributes (38070)

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | If order is already imported should to acknowledge as successfully imported
| Fixed ticket? | Fixes 38385
| How to test?  | Unit tested

If order is already imported should be acknowledged (38385)

---

controllers/front/product.php

| Description?  | XML tag has to locate at first line otherwise an error occurs

xml tag has to locate at first line (40448)

---

controllers/front/product.php
shoppingfeed.php
src/Services/SfTools.php

| Description?  | If PrestaShop version is 1.6 and the compress the product feed is enabled, then an error occurs during feed generation
| Fixed ticket? | Fixes 40129
| How to test?  | Load the feed on PS 1.6

Error during xml feed creation (40129)

---

shoppingfeed.php
views/templates/hook/displayPDFInvoice.tpl

| Description?  | In case of Laredoute order, PDF get specific content on invoices. If you make a mass export, laredoute assignation keep assigned
| Fixed ticket? | Fixes 41053

Bugfix pdf assign mass export (41053)

---

controllers/admin/AdminShoppingfeedGeneralSettings.php

| Description?  | category list in the filters contains duplicate categories if PS is multishop

Selects categories in filters duplicate lines in multishop (40990)

---

classes/actions/ShoppingfeedOrderSyncActions.php

| Description?  | Fix batch id empty. In this case the next call will return all ticket from SF API that involved big troubles

Fix batch id empty

---

shoppingfeed.php

Use full namespace for SfTools, avoiding module install error on PHP 5.6
| Description?  | There was a "use" statment in main module file, blocking the install on a PHP 5.6 server.
| How to test?  | Try to zip / install the module on a old PS 1.6 with PHP 5.6.

Compatibility for PHP 5.6 - SfTools

---

202/tests/ProductSerializer/TestAttributeTestCase.php
src/Services/ProductAttributeCombination.php
src/Services/ProductSerializer.php

| Description?  add field 'min quantity for sale'
| Fixed ticket? | Fixes #41039
| How to test?  | Unit test

ProductSerializer - add field 'min quantity for sale' (41039)

---

202/tests/OrderImport/OrderRulesTestingTest.php
src/OrderImport/Rules/TestingOrder.php
translations/fr.php

| Description?  | update rule testing order
| Fixed ticket? | Fixes #40564.
| How to test?  | Unit test.

Add configuration for Test order not only canceled after import (40564)

---

src/OrderImport/Rules/ShippedByMarketplace.php

Test array key isset before trying to access it.
| Description?  | Fix issue of Undefined index: env in OrderImport
| Fixed ticket? | Fixes #307
| How to test?  | No more php warning `Undefined index: env in OrderImport` in order synchronisation cron task.

Address issue #307: Undefined index: env in OrderImport 

---

src/OrderImport/Rules/AbstractColissimo.php
src/OrderImport/Rules/MonechelleColissimo.php

| Description?  | company is a mandatory field for colissimo carriers. The following modifications use a string 'undefined' if a company is not provided. Also they try extract the company name from the 'lastName' of  Monechelle shipping address.
| Fixed ticket? | Fixes 43707

Add company name on colissimo address for ManoMano (43707)

---

controllers/front/syncOrder.php

| Description?  | Automatic cleaning of the old order task doesn't work

Fix cleaning of old task order status sync (42833)

---

controllers/front/syncOrder.php

| Description?  | The sync Order cron throw an error and return false instead of continuing the process with following 
| Fixed ticket? | Fixes 

Sync Order task throw an error and return false instead of continuing (43970)

---

controllers/admin/AdminShoppingfeedOrderImportRules.php

| Description?  | fix for the warning on the configuration page
| Fixed ticket? | Fixes 43962

Fix warning on the configuration page (43962)

---

composer.json
src/OrderImport/GLS/CartCarrierAssociation.php
src/OrderImport/Rules/GlsRule.php

| Description?  | Apply the GLS rule even if the relay point id is absent (in the case of "Home delivery"). 

Make the relay point id an optional for gls rule (44516)

---

controllers/front/syncOrder.php
controllers/front/syncProduct.php

| Description?  | If multishop is used, and several tokens are configured (for each shop), and the prices are different according to the shop, then the prices are  incorrect since the wrong shop is taken into account.
| Fixed ticket? | Fixes 44375

Set a shop in a context according to a token configurations (44375)

---

controllers/admin/AdminShoppingfeedGeneralSettings.php

| Description?  | Incorrect displaying the switch option 'Real-time synchronization'

Fix switch option display Real-time sync (45406)

---

classes/ShoppingfeedApi.php
classes/actions/ShoppingfeedOrderImportActions.php
classes/actions/ShoppingfeedOrderSyncActions.php
controllers/admin/AdminShoppingfeedOrderImportRules.php
shoppingfeed.php
translations/fr.php
vendor/prefixed/shoppingfeed/php-sdk/src/Api/Order/OrderOperation.php

| Description?  | Current PR takes into account the API modifications and adopts the existing used calls to the new requirements, namely sending internal  SF order ID in the order operation calls ship/cancel/refund/acknowledge.
In addition, there is an added possibility to apply the status 'delivered'.
| Fixed ticket? | Fixes 35364

Feature/35364 using id order in api calls + sending the status 'Delivered'

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | The property OrderCarrier->date_add is not valid
| Fixed ticket? | Fixes 46127

Exception throw on orderCarrier date_add

---

shoppingfeed.php

| Description?  | Rename of hook deleteProductAttribute

Rename deprecated hook actionDeleteProductAttribute (47112)

---

classes/ShoppingfeedPreloading.php

| Description?  | Error a product update. json_decode(): Passing null to parameter on product feed
| Fixed ticket? | Fixes 47566

json_decode(): Passing null to parameter on product feed (47566)

---

src/OrderImport/GLS/CartCarrierAssociation.php

| Description?  | In case of import orders with GLS, the rule trigger a fatal error whith PS 1.6.
| Fixed ticket? | Fixes 47842

Fix GLS _DB_PREFIX_ for PS 1.6 (47842)

---

src/OrderImport/Rules/ColissimoRule.php

| Description?  | do not look for a colissimo point id if an order comes from eBay
| Fixed ticket? | Fixes 48460

Do not look for a point id if an order comes from eBay (48460)

---

views/js/form_config_filter.js

Fixes [https://github.com/shoppingflux/module-prestashop/security/code-scanning/1](https://github.com/shoppingflux/module-prestashop/security/code-scanning/1)
To fix the problem, we need to ensure that the text retrieved from the DOM is properly escaped before being inserted as HTML. This can be achieved by using a method that sets the text content instead of HTML content, such as `.text()` instead of `.html()`. This will prevent any HTML meta-characters in the text from being interpreted as HTML.
- Replace the use of `.html()` with `.text()` to ensure that the text is properly escaped.
- Specifically, change line 53 in the file `views/js/form_config_filter.js`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 1: DOM text reinterpreted as HTML

---

shoppingfeed.php
src/Services/SfTools.php

| Description?  | If an reference association is 'Default value (ID product with ID combination)' then a reference like '4G-WYBQ-FKKN' is parsed incorrect. Expected result is no product found, actual result is a product with id 4.
| Fixed ticket? | Fixes 50520

Fix mapping prestashop product (50520)

---

shoppingfeed.php
src/Services/SfTools.php

| Description?  | If an reference association is 'Default value (ID product with ID combination)' then a reference like '4G-WYBQ-FKKN' is parsed incorrect. Expected result is no product found, actual result is a product with id 4.
| Fixed ticket? | 50521

 Fix mapping prestashop product (50521) #408 

---

shoppingfeed.php

| Description?  | A goal is blocking not only order confirmation messages but messages about an order status update

refs #43794 block notification about an order status update

---

classes/ShoppingfeedApi.php
src/OrderImport/Rules/ShippedByMarketplace.php

| Description?  | If order is considered as both 'shipped by marketplace' and 'shipped' the restriction import date which should be taken into an account is one for 'shipped by marketplace'.

refs #50038 filtering order by date

---

shoppingfeed.php

| Description?  | If send email in the module is set  to no in the module, allow notifications of new orders to the administator from the ps_emailalert module.
| Fixed ticket? | Fixes 52096
| How to test?  | NC

Allow sending email for ps_emailalert (52096)

---

classes/actions/ShoppingfeedOrderSyncActions.php
shoppingfeed.php

| Description?  | Do not sync orders that were imported more than 3 months ago

Do not retry order sync after 3 months (51741)

---

classes/ShoppingfeedApi.php

| Description?  | Error message on log when launching order task: Connot import order : syntax error, unexpected ')' modules/shoppingfeed/classes/ShoppingfeedApi.php:328
| How to test?  | Import an order.

Remove comma in method syntax error under php 8
