shoppingflux/module-prestashop

202/build.xml
controllers/front/syncOrder.php
shoppingfeed.php
src/Services/ProductSerializer.php
views/templates/admin/shoppingfeed_general_settings/product_filter_rules.tpl

bugfix - fix update statuts
bugfix - fiw weigh for production variation
featrue - default configuration 'large default' for product feed
bugfix  - add hook deleteProductAttribute
bugfix  - fix translation

develop > release/1.5.x

---

classes/ShoppingfeedOrder.php
classes/actions/ShoppingfeedOrderImportActions.php
classes/actions/ShoppingfeedOrderSyncActions.php
upgrade/install-1.5.1.php

bugfix - fix update order status

fix update order status

---

src/Services/ProductSerializer.php

bugfix #28668 - sync product - wrong category in a multishop environment

refs #28668 wrong category in a multishop environment

---

202/build.xml
classes/ShoppingfeedPreloading.php
classes/actions/ShoppingfeedOrderImportActions.php
classes/actions/ShoppingfeedOrderSyncActions.php
controllers/front/product.php
controllers/front/syncOrder.php
shoppingfeed.php
src/OrderImport/Rules/ChangeStateOrder.php
src/OrderImport/Rules/Mondialrelay.php
src/OrderImport/Rules/RueducommerceMondialrelay.php
src/Services/ProductSerializer.php
upgrade/install-1.5.6.php

bugfix #28957 - fix amount order
bugfix #29002 - enable feature with '0' value
feature #29001 - add more log for update order
bugfix #28982 - fix breadcrumb for product feed
feature #28961 - send log to sf when customer create fail
feature #28960 - add attachment to product feed
bugfix #28955 - fix rule for 'Mondial Relay'
bugfix #28880 - prevent change state order when state is "PS_OS_PAYMENT"

develop > master

---

202/tests/OrderImport/OrderImportDPDManomanopro.php
202/tests/OrderImport/OrderRulesManomanoDpdRelaisTest.php
202/tests/OrderImport/dataset/order-manomanopro.json
src/OrderImport/Rules/ManomanoDpdRelais.php

| Description?  | Add DPD relay dependancy for ManoMano Pro 
| Fixed ticket? | Fixes 34351
| How to test?  | Phpunit tests

Add DPD relay dependancy for ManoMano Pro 

---

202/tests/OrderImport/OrderImportWithConfigTest.php
classes/actions/ShoppingfeedOrderImportActions.php
src/OrderImport/Rules/AbstractColissimo.php
src/OrderImport/Rules/ColizeyColissimo.php
src/OrderImport/Rules/ManomanoDpdRelais.php
translations/fr.php

| Description?  | Get address email from shippingAddress if billingAdress email is not valid
| Fixed ticket? | Fixes 34678
| How to test?  | Validate by unit test

 Get address email from shippingAddress if billingAdress email is not valid

---

202/build.xml

Bump 1.7.1

---

shoppingfeed.php

| Description?  | Fix hook dispatcher namespace call

Fix hook dispatcher

---

src/Services/CdiscountFeeProduct.php

refs #35428 cdiscount fee product. error during creating

---

translations/fr.php

| Description?  | Release 1.8.0
| Type?         | release

Release 1.8.0 (final)

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | load carrier from sfcarrier
| Fixed ticket? | Fixes #35398

refs #35398 - fix carrier retrieval after rules import

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | update sock for pack for each item.
| Fixed ticket? | Fixes #35685

Import error on pack if a reference has no stock

---

shoppingfeed.php

| Description?  | Enable  ManomanoColissimo and MonechelleColissimo rule to the list of the available rules
| Fixed ticket? | Fixes #34374
| How to test?  | see the list of rules in backoffice (shoppingfeed > orders settings)

Enable  ManomanoColissimo and MonechelleColissimo rule

---

202/docker/run_for_unittest.sh
202/phpunit.xml
202/tests/OrderImport/OrderImportSimpleTest.php
classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | Removing gift product during order import process.
| Fixed ticket? | Fixes #35998
| How to test?  | Test by Unit test. Add a cart rules that add a product as "gift" on order. This gift should be removed.

Removing gift product during order import process

---

.github/workflows/phpunit.yml
202/docker/run_for_unittest.sh
202/tests/OrderImport/OrderImportMondialRelaisTest.php
202/tests/OrderImport/OrderImportStockTest.php
202/tests/OrderImport/dataset/order-colizey-mondialrelais.json
202/tests/OrderImport/dataset/order-stock.json
src/OrderImport/Rules/AbstractMondialrelay.php
src/OrderImport/Rules/GoSportMondialrelay.php

| Description?  | add new rules for mondial relais go sport.
| Type?         | improvement 
| Fixed ticket? | Fixes #{35281

Add mondialrelais for Go Sport

---

.htaccess

| Description?  | Add htaccess in the root path to unauthorize all none static files
| Fixed ticket? | Fixes 36093
| How to test?  | Call https://Myshop.domain.tld/modules/shoppingfeed/test.php > should return a 403 Forbidden status

Add htaccess in the root path to unauthorize all none static files

---

composer.json
upgrade/install-1.8.1.php

| Description?  | release 1.8.2
| Type?         | release

release 1.8.2

---

202/docker/run_for_unittest.sh
202/tests/OrderImport/OrderShippedByMarketplaceTest.php
202/tests/OrderImport/dataset/order-shipped-afn.json
202/tests/OrderImport/dataset/order-shipped-clogistique.json
202/tests/OrderImport/dataset/order-shipped-epmm.json
202/tests/OrderImport/dataset/order-shipped-fulfilledByChannel.json
controllers/admin/AdminShoppingfeedOrderImportRules.php
shoppingfeed.php
src/OrderImport/Rules/ShippedByMarketplace.php
translations/fr.php

| Description?  | Import already delivered order 
| Fixed ticket? | Fixes 35445
| How to test?  | by Unit test

Import already delivered order (35445)

---

controllers/admin/AdminShoppingfeedOrderImportRules.php
shoppingfeed.php
src/Services/OrderTracker.php
translations/fr.php

| Description?  | Send orders taken on the PrestaShop
| Fixed ticket? | Fixes 30199
| How to test?  | ?

Send orders taken on the PrestaShop (30199)

---

package-lock.json

Reverts shoppingflux/module-prestashop#198

Revert "Bump engine.io and browser-sync"

---

202/build.xml
classes/ShoppingfeedToken.php

| Description?  | fix main issue code review.
| Fixed ticket? | Fixes #36994

Realease 1.8.3

---

202/phpstan/phpstan.neon
202/tests/ProductSerializer/TestAttributeTestCase.php
classes/ShoppingfeedPreloading.php
classes/actions/ShoppingfeedOrderImportActions.php
controllers/admin/AdminShoppingfeedAccountSettings.php
controllers/admin/AdminShoppingfeedGeneralSettings.php
controllers/admin/AdminShoppingfeedOrderImport.php
controllers/admin/AdminShoppingfeedOrderImportRules.php
controllers/front/syncAll.php
shoppingfeed.php
src/OrderImport/RulesManager.php
src/ProductFilter/AttributeFilter.php
src/ProductFilter/BrandFilter.php
src/ProductFilter/CategoryFilter.php
src/ProductFilter/FeatureFilter.php
src/ProductFilter/SupplierFilter.php
src/Services/OrderTracker.php
src/Services/ProductSerializer.php
vendor/totpsclasslib/src/Extensions/ProcessMonitor/Controllers/Front/CronController.php
vendor/totpsclasslib/src/Extensions/ProcessMonitor/ProcessMonitorHandler.php

| Description?  | fix function translation.
| Fixed ticket? | Fixes #37427.
| How to test?  | .

refs #37427 - fix function translation for ps 1.6.1.24

---

.github/workflows/php.yml
shoppingfeed.php

| Description?  | Compatibily PS 8.0 and php 8.0 & 8.1

Compatibily PS 8.0 and php 8.0 & 8.1

---

classes/actions/ShoppingfeedOrderImportActions.php
shoppingfeed.php
src/OrderImport/Rules/Cdiscount.php
src/Services/CdiscountFeeProduct.php

…om cdiscount
| Description?  | create cdiscount fee product only when import order from cdiscount.
| Type?         | improvement 
| Fixed ticket? | Fixes #36546

add CDiscount fee product not all times (36546)

---

src/OrderImport/Rules/AmazonEbay.php

| Description?  | fix rule amazonEbay
| Fixed ticket? | Fixes #36944

Refs#36944 update rule amazonebay

---

controllers/admin/AdminShoppingfeedProcessMonitor.php
controllers/front/syncAll.php

| Description?  | Using token in addition to secure_key in cron
| Fixed ticket? | Fixes 36176
| How to test?  | Load the front crontroller with one token

Using token in addition to secure_key in cron (36176)

---

202/tests/OrderImport/OrderImportSimpleTest.php
classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | add marketplace reference in transaction_id payement.
| Fixed ticket? | Fixes #37799
| How to test?  | unit test

add marketplace reference as payement transaction ID (37799)

---

src/Services/OrderTracker.php

| Description?  | Fix order tracking
| Fixed ticket? | Fixes 30199
| How to test?  | -

Fix order tracking (30199)

---

202/tests/OrderImport/GaleriesLafayetteColissimoTest.php
202/tests/OrderImport/OrderImportCDiscountTest.php
202/tests/OrderImport/OrderImportDPDManomanopro.php
202/tests/OrderImport/OrderImportManoManoDpdRelaisWithDoubleTaxOnProductTest.php
202/tests/OrderImport/OrderImportMondialRelaisTest.php
202/tests/OrderImport/OrderImportSimpleTest.php
202/tests/OrderImport/OrderImportStockTest.php
202/tests/OrderImport/OrderImportVerifyCurrencyTest.php
202/tests/OrderImport/OrderImportWithConfigTest.php
202/tests/OrderImport/OrderImportZalandoTest.php
202/tests/OrderImport/OrderRulesAmazonManomanoTvaTest.php
202/tests/OrderImport/OrderRulesColissimoTest.php
202/tests/OrderImport/OrderShippedByMarketplaceTest.php
202/tests/OrderImport/OrderSplittingTest.php
classes/actions/ShoppingfeedOrderImportActions.php
controllers/front/syncOrder.php

| Description?  | import order with cart in token language.
| Fixed ticket? | Fixes #38247

Import order with token language (38247)

---

202/docker/run_for_unittest.sh
202/tests/OrderImport/OrderImportManoManoDpdRelaisWithDoubleTaxOnProductTest.php
202/tests/OrderSync/OrderSyncStatusTest.php
classes/ShoppingfeedApi.php
classes/actions/ShoppingfeedOrderImportActions.php
classes/actions/ShoppingfeedOrderSyncActions.php

| Description?  | Update order status managed by batch instead of tickets.
| Fixed ticket? | Fixes 38524

Update order status managed by batch instead of tickets (38524)

---

202/tests/OrderImport/OrderShippedByMarketplaceTest.php
classes/actions/ShoppingfeedOrderImportActions.php
src/OrderImport/Rules/ShippedByMarketplace.php

| Description?  | change order skipping in case of orders shipped by marketplace to escape
| Fixed ticket? | Fixes 38243

Fix order skipping (38243)

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | Adding log before removing order detail tax
| Fixed ticket? | Fixes 38595
| How to test?  | NC

Adding log before removing order detail tax (38595)

---

src/Hook/BackOfficeHeader.php
translations/fr.php

| Description?  | Translations of carrier BO header message
| Fixed ticket? | Fixes 38911
| How to test?  | Remove default carrier set to compute the xml feed. See the message.

Translations of carrier BO header message (38911)

---

shoppingfeed.php
upgrade/install-1.10.0.php

| Description?  | Adding additional index to the table shoppingfeed_preloading
| Fixed ticket? | Fixes 38308
| How to test?  | Time to load an XML in a big catalog with multitoken token

Added indexes to preloading table (38308)

---

controllers/admin/AdminShoppingfeedGeneralSettings.php

| Description?  | Sync product section was moved to the factory settings.
| Fixed ticket? | Fixes 38934
| How to test?  | Turn into factory settings and update parameters

Move product realtime synchro into factory settings (38934)

---

shoppingfeed.php
views/templates/hook/displayPDFInvoice.tpl

| Description?  | Added the SF order id to the order invoice

refs #38854 Order ID in the pdf invoice

---

202/tests/ProductSerializer/TestAttributeTestCase.php
src/Services/ProductSerializer.php

| Description?  | Apply VAT on ecotax on the feed
| Fixed ticket? | Fixes 39720

Apply VAT on ecotax on the feed (39720)

---

src/OrderImport/Rules/ShippedByMarketplace.php
translations/fr.php

| Description?  | Update label shipped by marketplace
| Fixed ticket? | Fixes 39547
| How to test?  | Just see the new label in Settings > Orders feed

Update label shipped by marketplace (39547)

---

classes/ShoppingfeedProduct.php

| Description?  | Taking into account the shop context while searching for the product by reference
| Fixed ticket? | Fixes 40434

Product feed taking into account id_shop (40434)

---

202/tests/OrderImport/OrderRulesAmazonEbayTest.php
202/tests/OrderImport/dataset/order-miravia.json
src/OrderImport/Rules/AmazonEbay.php

| Description?  | set correct first/last name for the orders from maravia marketplace
| Fixed ticket? | Fixes 40197

Miravia orders split name (40197)

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | Small optimization of the order acknowledge process

refs #40722 acknowledge order optimization

---

classes/actions/ShoppingfeedProductSyncStockActions.php
translations/fr.php

| Description?  | Update logs in case of sync stock
| Fixed ticket? | Fixes 41463 
| How to test?  | NC

Update logs in case of sync stock (41463)

---

controllers/front/syncOrder.php

| Description?  | Adjust the maximum order importation date.
| Fixed ticket? | Fixes 41653

Adjust order importation date 30 rolling days (41653)

---

202/tests/OrderImport/OrderImportRetifTest.php
src/OrderImport/Rules/SkipTax.php

| Description?  | Skip tax in case of Retif marketplace
| Fixed ticket? | Fixes 41868

Skip tax in case of Retif marketplace (41868)

---

controllers/front/syncOrder.php

| Description?  | Adjust order importation date 30 rolling days (41653). Fix bug of #288 
| Fixed ticket? | Fixes 41653

Adjust order importation date 30 rolling days (41653) bis

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | update stock with shop id.
| Fixed ticket? | Fixes #42371.

Fix multishop stock management (42371)

---

src/Services/ProductSerializer.php

| Description?  | Fix shipping cost by weight for variations.
| Fixed ticket? | Fixes 42561
| How to test?  | Configure a carrier with cos by weight<br>Configure a weight of product in a range of shipping cost<br>Configure a weight of an attribute in an other range of shipping cost<br>Load the XML feed and verify the shippingcost node of you custom product

Fix shipping cost by weight for variations (42561)

---

202/tests/OrderImport/dataset/order-amazon-prohibited-symbols.json
src/OrderImport/OrderData.php

| Description?  | the dots in the first and last name are invalid.
| Fixed ticket? | Fixes #42601.
| How to test?  | unit test OrderRulesSymbolConformityTest.

Replace dots in firstname and lastname (42601)

---

controllers/admin/AdminShoppingfeedAccountSettings.php
controllers/admin/AdminShoppingfeedDiagnostic.php
translations/fr.php
views/templates/admin/shoppingfeed_compatibility/account_settings.tpl
views/templates/admin/shoppingfeed_compatibility/diagnostic.tpl
views/templates/admin/shoppingfeed_compatibility/message.tpl

| Description?  | add warning shoppingfeed compatibility.
| Fixed ticket? | Fixes #42404.
| How to test?  | .

Add warning shoppingfeed compatibility (42404)

---

202/tests/OrderImport/dataset/manomano-epmm-missing-carrier.json
202/tests/OrderImport/dataset/order-gls.json
202/tests/OrderImport/dataset/order-manomano-colissimo.json
202/tests/OrderImport/dataset/order-manomano-with-tva-num.json
202/tests/OrderImport/dataset/order-manomano.json
202/tests/OrderImport/dataset/order-manomanopro.json
src/OrderImport/Rules/AmazonManomanoTva.php

| Description?  | update field billing fiscal number.
| Fixed ticket? | Fixes #42285.

Update field billing fiscal number for manomano (42285)

---

src/OrderImport/GLS/Adapter.php
src/OrderImport/GLS/CartCarrierAssociation.php
src/OrderImport/Rules/GlsRule.php

| Description?  | Fix nkmGLS breacking changes
| Fixed ticket? | Fixes 42310
| How to test?  | Unit tested

Fix nkmGLS breacking changes (42310)

---

src/OrderImport/Rules/GlsRule.php

| Description?  | Use syntax that is available with PHP 7.2 and lower
| Fixed ticket? | Fixes 43122

Compatibility with php 7.2.x and lower (43122)

---

202/build.xml
src/OrderImport/Rules/GlsRule.php
src/OrderImport/Rules/ShippedByMarketplace.php

| Description?  | Release 1.10.5
| Type?         | release

Release 1.10.5

---

src/OrderImport/Rules/AbstractMondialrelay.php

| Description?  | exception during SoapClient initialization 
| Fixed ticket? | Fixes 43708

Fix Mondial Relay SOAP client domain (43708)

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | Creation of the order-carrier association if it it's need
| Fixed ticket? | Fixes 43219

Creation of the order-carrier association if it it's need (43219)

---

src/Services/OrderTracker.php

| Description?  | Sending the necessary headers 

Update Header User-Agent for tracking (43218)

---

vendor/prefixed/shoppingfeed/php-sdk/src/Http/Adapter/Guzzle6Adapter.php

| Description?  | added prefix to make sure that a correct version of guzzle is used

Add prefix on the namespace for guzzle Adapter (41355)

---

shoppingfeed.php

| Description?  | Improvement of the verification the module shoppingfluxexport
| Fixed ticket? | Fixes 44518

Improvement of the verification the module shoppingfluxexport (44518)

---

classes/actions/ShoppingfeedProductSyncPreloadingActions.php

| Description?  | product is not updated in a preloading table
| Fixed ticket? | Fixes 44878
| How to test?  | Configure multishop env => Configure the token for the non-default shop => Deactivate some product in the default shop => Modify a product in the non-default shop => Check if the product is modified in XML product feed.

Multishop / some products are not updated (44878)

---

202/docker/run_for_unittest.sh
202/tests/OrderImport/OrderRulesColissimoTest.php
202/tests/OrderImport/dataset/order-bhv-colissimo.json
202/tests/OrderImport/dataset/order-manomano-colissimo.json
202/tests/OrderImport/dataset/order-veepeegroup-colissimo.json
shoppingfeed.php
src/OrderImport/Rules/BhvColissimo.php
src/OrderImport/Rules/ManomanoColissimo.php
src/OrderImport/Rules/VeepeegroupColissimo.php

| Description?  | a new rules for Veepeegroup/Bhv and Colissimo
| Deprecations? | yes
| Fixed ticket? | Fixes 45599

Add import rule VeepeegroupColissimo (45599)

---

classes/ShoppingfeedApi.php
classes/ShoppingfeedToken.php
classes/actions/ShoppingfeedOrderSyncActions.php
classes/actions/ShoppingfeedProductSyncPriceActions.php
classes/actions/ShoppingfeedProductSyncStockActions.php
controllers/admin/AdminShoppingfeedAccountSettings.php
controllers/admin/AdminShoppingfeedGeneralSettings.php
controllers/front/product.php
controllers/front/syncOrder.php
controllers/front/syncProduct.php
shoppingfeed.php
upgrade/install-1.10.8.php
views/js/account-settings-page.js
views/templates/admin/shoppingfeed_account_settings/_partial/button-get-store-id.tpl
views/templates/admin/shoppingfeed_account_settings/token-form.tpl

| Description?  | Adding the possibility configure storeID + using feed_key 
| Fixed ticket? | Fixes 44802 46128
| How to test?  | Fill in the registration form

Manage multi storeID on a token and add feed key distinct to token (44802 & 46128)

---

classes/ShoppingfeedToken.php
controllers/admin/AdminShoppingfeedAccountSettings.php
shoppingfeed.php

| Description?  | merchant info in a token list

refs #46128 merchant in token list

---

src/Services/ProductAttributeCombination.php
src/Services/ProductSerializer.php

| Description?  | Add missing mpn on variations
| Fixed ticket? | Fixes 

Add mpn on variations

---

controllers/admin/AdminShoppingfeedGeneralSettings.php

| Description?  | Availability of gzip option
| Fixed ticket? | Fixes 46627

Availability of gzip option (46627)

---

controllers/admin/AdminShoppingfeedGeneralSettings.php

| Description?  | error during saving factory conf

refs #46627 error during save factory conf

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | Catching all exceptions during the order validation

refs #46836 catching exceptions during an order validation

---

controllers/front/product.php

| Description?  | access to the product XML by an old format URI

refs #46904 handle the old-format URL

---

src/OrderImport/Rules/MondialrelayRule.php

| Description?  | PrestaShop error: 3 arguments are required, 2 given

refs #46735 error fix

---

src/Services/ProductAttributeCombination.php

| Description?  | Products remain out of the index
| Fixed ticket? | Fixes 47539
| How to test?  | Problem occurs if PS version lower than 1.7.7.0 and the mode 'Debug' is enabled

Warning during product indexing (47539)

---

classes/ShoppingfeedToken.php
src/OrderImport/Rules/AmazonEbay.php

| Description?  | Incorrect address parsing if an order comes from amazon/ebay/laredoute and both a first name and a last name provided
| Fixed ticket? | Fixes 47367
| How to test?  | Unit tests

Wrong address parsing (47367)

---

classes/ShoppingfeedPreloading.php

| Description?  | random removing/adding products in xml

Set order explicitly on preloading product request (47756)

---

src/OrderImport/Rules/Cdiscount.php

| Description?  | Generating a reference of the cdiscount fees according to the module configurations
| Fixed ticket? | Fixes 47744

Generating a reference of the cdiscount fees according to the module configurations (47744)

---

202/docker/run_for_unittest.sh
202/tests/ProductSerializer/TestAttributeTestCase.php
src/Services/ProductSerializer.php

| Description?  | add ttributes multiples in xml.
| Fixed ticket? | Fixes #48163.
| How to test?  | unit test.

Add multiple features on product feeds (48163)

---

controllers/front/syncAll.php

| Description?  | run 'init' on child crons 
| Fixed ticket? | Fixes 48174

SyncAll execution precess compat PS 8+ (48174)

---

shoppingfeed.php
src/OrderImport/Rules/Cdiscount.php
translations/fr.php

| Description?  | a new option in BO to enable/disable adding cdiscount fees to an imported order
| Fixed ticket? | Fixes 48305

Add option in BO to enable/disable adding cdiscount fees (48305)

---

src/OrderImport/Rules/ColissimoRule.php

| Description?  | Determes conditions when relay point id may be taken from shippingAddress.other
| Fixed ticket? | Fixes 48780

Relay point id in shippingAddress.other (48780)

---

classes/actions/ShoppingfeedProductSyncPreloadingActions.php

| Description?  | incorrect tax in product xml
| Fixed ticket? | Fixes 48934

Wrong tax in product xml in multitoken multishop (48934)

---

src/Services/ProductSerializer.php

| Description?  | Add supplier reference from dedicated table
| BC breaks?    | yes (if a feed use deprecated supplier reference)
| Deprecations? | yes
| Fixed ticket? | Fixes 49020

Add supplier reference from dedicated table (49020)

---

classes/ShoppingfeedApi.php
classes/actions/ShoppingfeedOrderSyncActions.php

| Description?  | to consider the store id when request tickets 
| Fixed ticket? | Fixes 49015

Get ticket from a correct store (49015)

---

.github/workflows/php.yml
.github/workflows/phpunit.yml

| Description?  | Upgrade CI/CD component
| Type?         |  improvement 
| Fixed ticket? | Fixes 

upgrade actions/cachev4

---

controllers/front/product.php

1.x Export product - fix images variation (49175)

---

controllers/front/product.php

| Fixed ticket? | Fixes 49175.

Fix variation image without hierarchical (49175)

---

controllers/front/product.php
src/Services/ProductSerializer.php

| Description?  | 
| Fixed ticket? | Fixes #49175.

Export product - fix images variation (49175)

---

controllers/front/product.php

Link/weight/ecotax/attributes on feed on relase 1.x (49175)

---

controllers/front/product.php

Link/weight/ecotax/attributes on feed on relase 2.x (49175)

---

translations/fr.php

| Description?  | Error message: Unknown format specifier " "

refs #50322 error on diagnostic page

---

shoppingfeed.php

refs #49022 make uploading invoice available

---

controllers/front/syncOrder.php

Fix store ID on order status sync (multitoken and storeID)

---

src/OrderImport/Rules/MondialrelayRule.php

| Description?  | The method addAfterCartCreation() has been added to the rule MondialrelayRule

refs #50094 MondialrelayRule::afterCartCreation()

---

classes/ShoppingfeedApi.php

Add param in the hook ShoppingfeedOrderImportCriteria

---

src/Services/ProductSerializer.php

| Description?  | Redundant images appear in the catalog XML

Redundant images in the catalog xml (50672)

---

controllers/admin/AdminShoppingfeedOrderImportRules.php
translations/fr.php

| Description?  | translations

refs #35363 translation

---

classes/actions/ShoppingfeedOrderSyncActions.php
controllers/admin/AdminShoppingfeedOrderImportRules.php
src/OrderInvoiceSync/Hub.php
translations/fr.php
upgrade/install-2.0.0.php

| Description?  | improvement of feature 'send invoice'

Feature send invoice (49022)

---

classes/ShoppingfeedApi.php
classes/actions/ShoppingfeedOrderImportActions.php
vendor/prefixed/shoppingfeed/php-sdk/src/Api/Order/Operation.php

refs #49022 update shoppingfeed php-sdk

---

src/Services/ProductSerializer.php

| Description?  | Redundant images appear in the catalog XML

refs #50671 redundant images in the catalog xml

---

202/build.xml
shoppingfeed.php

Fix hook method name (43794)

---

translations/fr.php

| Description?  | typo in translation

refs #50284 typo in translation

---

src/Services/ProductSerializer.php

| Description?  | Wrong carrier price in product xml in some PrestaShop environment (1.6.x)

Carrier price and currency (51137)

---

composer.json
vendor/prefixed/symfony/deprecation-contracts/function.php

| Description?  | Error: Attempted to call function "trigger_deprecation" from namespace "ShoppingFeed\Sdk\Api\Session".

refs #51568 deprecation error

---

202/build.xml
composer.json
vendor/prefixed/symfony/deprecation-contracts/function.php

| Description?  | Release 2.0.2
| Type?         | Release
| Fixed ticket? | Fixes #428

🚀 Release 2.0.2

---

controllers/front/product.php

| Description?  | Wrong default value of the configuration "Layout of variations"

refs #51699 default value for "Layout of variations"

---

src/Services/OrderTracker.php

| Description?  | sql error: the table customer_ip is not found
| Fixed ticket? | Fixes 51925

Sql error: the table customer_ip is not found (51925)

---

src/Services/OrderTracker.php

| Description?  | sql error: The table customer_ip is not found
| Fixed ticket? | Fixes 51926

Sql error: The table customer_ip is not found (51926)

---

202/build.xml
classes/ShoppingfeedApi.php
classes/ShoppingfeedTaskOrder.php
classes/actions/ShoppingfeedOrderSyncActions.php
controllers/front/product.php
controllers/front/syncOrder.php
src/OrderImport/Rules/ShippedByMarketplace.php
src/Services/OrderTracker.php
upgrade/install-2.0.3.php

| Description?  | Release 2.0.3
| Type?         | release
| Fixed ticket? | Fixes #437

Release 2.0.3

---

classes/ShoppingfeedAdminController.php
controllers/front/syncOrder.php
shoppingfeed.php
translations/fr.php

| Description?  | Prevent an order import and show appropriate message if the catalog mode is enabled

refs #46117 catalog mode

---

classes/Compatibility/SpecificPriceFormatter.php
classes/ShoppingfeedApi.php
classes/actions/ShoppingfeedOrderSyncActions.php

| Description?  | Add hooks to manage custom multi-tracking (51709)
| Fixed ticket? | Fixes 51709

Add hooks to manage custom multi-tracking (51709)

---

classes/actions/ShoppingfeedOrderImportActions.php
classes/actions/ShoppingfeedProductSyncPreloadingActions.php

| Description?  | applying SF tax rate to shipping

Applying sf tax to shipping (52390)

---

classes/actions/ShoppingfeedOrderSyncActions.php
shoppingfeed.php

| Description?  | Warning if some sync order states are not adjusted

Order state sync (52712)

---

classes/actions/ShoppingfeedOrderSyncActions.php
shoppingfeed.php

| Description?  | Warning if some sync order states are not adjusted

refs #52711 order state sync

---

classes/actions/ShoppingfeedOrderImportActions.php

| Description?  | Handling free delivery 
| Fixed ticket? | Fixes 52390

Handling free delivery (52390)

---

controllers/admin/AdminShoppingfeedAccountSettings.php

refs #51957 do not show cloud sync form

---

classes/ShoppingfeedApi.php

| Description?  | Null Coalescing Assignment Operator should be removed
| How to test?  | import order in PHP 7.1

Fix syntax error under php7.4

---

shoppingfeed.php

| Description?  | set module key

module key
